backend:
  name: git-gateway
  branch: main
  login: true

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "portfolio"
    label: "Portofolio"
    folder: "src/content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Deskripsi", name: "body", widget: "markdown" }
      - { label: "Gambar", name: "image", widget: "image" }
